"""Court-ready reporting (certify) tests."""

import json
import tempfile
from pathlib import Path

from opensleuth import certify as C


def _mk_case(root: Path):
    (root / "sub").mkdir(parents=True)
    (root / "sms.db").write_bytes(b"evidence payload")
    (root / "photo.jpg").write_bytes(b"\xff\xd8fakejpeg")
    (root / "sub" / "note.txt").write_text("note")


def test_certify_creates_artifacts():
    with tempfile.TemporaryDirectory() as td:
        case = Path(td) / "case"
        out = Path(td) / "out"
        _mk_case(case)
        r = C.certify(case, out, "Jane Doe")
        assert r["file_count"] == 3
        assert (out / C.MANIFEST_NAME).exists()
        assert (out / C.REPORT_NAME).exists()
        assert (out / C.REPORT_HTML).exists()
        assert out / "seal.key"  # auto-generated key
        report = json.loads((out / C.REPORT_NAME).read_text())
        assert report["examiner"] == "Jane Doe"
        assert len(report["seal"]) == 64
        html = (out / C.REPORT_HTML).read_text()
        assert "Sealed Evidence Report" in html and "Jane Doe" in html


def test_verify_ok_uses_autogenerated_key():
    with tempfile.TemporaryDirectory() as td:
        case = Path(td) / "case"
        out = Path(td) / "out"
        _mk_case(case)
        C.certify(case, out, "Jane Doe")
        v = C.verify(out / C.REPORT_NAME)
        assert v["seal_valid"] is True
        assert v["tampered"] == 0
        assert v["integrity_ok"] is True


def test_verify_detects_tamper():
    with tempfile.TemporaryDirectory() as td:
        case = Path(td) / "case"
        out = Path(td) / "out"
        _mk_case(case)
        C.certify(case, out, "Jane Doe")
        (case / "sms.db").write_bytes(b"tampered!")
        v = C.verify(out / C.REPORT_NAME)
        assert v["tampered"] == 1
        assert v["failures"][0]["relpath"] == "sms.db"
        assert v["failures"][0]["status"] == "TAMPERED"
        assert v["integrity_ok"] is False


def test_verify_detects_missing_file():
    with tempfile.TemporaryDirectory() as td:
        case = Path(td) / "case"
        out = Path(td) / "out"
        _mk_case(case)
        C.certify(case, out, "Jane Doe")
        (case / "photo.jpg").unlink()
        v = C.verify(out / C.REPORT_NAME)
        assert v["tampered"] == 1
        assert v["failures"][0]["status"] == "missing"


def test_verify_seal_invalid_with_wrong_key():
    with tempfile.TemporaryDirectory() as td:
        case = Path(td) / "case"
        out = Path(td) / "out"
        _mk_case(case)
        C.certify(case, out, "Jane Doe")
        # moving the seal.key away breaks the seal check
        (out / C.KEY_NAME).unlink()
        v = C.verify(out / C.REPORT_NAME)
        assert v["seal_valid"] is False


def test_passphrase_flow():
    with tempfile.TemporaryDirectory() as td:
        case = Path(td) / "case"
        out = Path(td) / "out"
        _mk_case(case)
        C.certify(case, out, "Jane Doe", passphrase="hunter2")
        assert not (out / C.KEY_NAME).exists()
        v = C.verify(out / C.REPORT_NAME, passphrase="hunter2")
        assert v["seal_valid"] is True
        v2 = C.verify(out / C.REPORT_NAME, passphrase="wrong")
        assert v2["seal_valid"] is False


def test_render_verify():
    v = {"report": "/x.json", "examiner": "J", "generated_at": "t",
         "file_count": 3, "seal_valid": True, "tampered": 0, "failures": [],
         "integrity_ok": True}
    out = C.render_verify(v)
    assert "INTEGRITY OK" in out
    v["seal_valid"] = False
    out = C.render_verify(v)
    assert "INVALID" in out